apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: exampleas.examples.io
spec:
  group: examples.io
  names:
    kind: ExampleA
    listKind: ExampleAList
    plural: exampleas
    singular: examplea
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
