apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    capabilities: Basic Install
  name: example-operator-b.v0.0.2
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: ExampleB
      name: examplebs.examples.io
      version: v1alpha1
      displayName: Example B
      description: Example B Custom Resource Definition
  displayName: Example Operator B
  description: An example operator (B)
  provider:
    name: Example Provider B
  links:
    - name: Source Code
      url: https://github.com/djzager/olm-playground
  keywords:
    - foo
    - bar
    - baz
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - example-operator-b
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - examples.io
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: example-operator-b
      deployments:
      - name: example-operator-b
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: example-operator-b
          strategy: {}
          template:
            metadata:
              labels:
                name: example-operator-b
            spec:
              containers:
              - command:
                - /usr/local/bin/ao-logs
                - /tmp/ansible-operator/runner
                - stdout
                image: docker.io/djzager/example-operator-b:v2
                imagePullPolicy: IfNotPresent
                name: ansible
                resources: {}
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
                  readOnly: true
              - env:
                - name: WATCH_NAMESPACE
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: example-operator-b
                image: docker.io/djzager/example-operator-b:v2
                imagePullPolicy: IfNotPresent
                name: operator
                resources: {}
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
              serviceAccountName: example-operator-b
              volumes:
              - emptyDir: {}
                name: runner
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  version: 0.0.2
  replaces: example-operator-b.v0.0.1
