apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: examplebs.examples.io
spec:
  group: examples.io
  names:
    kind: ExampleB
    listKind: ExampleBList
    plural: examplebs
    singular: exampleb
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
